version: 2

project_name: tetris-go

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    main: .
    binary: tetris-go
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
  - id: windows-amd64
    main: .
    binary: tetris-go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
    goarch:
      - amd64

archives:
  - id: bundles
    builds:
      - linux-amd64
      - windows-amd64
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - src: fonts/**
      - src: sounds/**

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

